name: archlinux
on:
  push:
    branches:
      - main
    paths:
      - "rootfs.Dockerfile"
      - "archlinux/rootfs.Dockerfile"
      - "archlinux/rootfs.sh"
  schedule:
    - cron: "0 0 * * 0"
env:
  TZ: Asia/Shanghai
jobs:
  build:
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          # registry.cn-hangzhou.aliyuncs.com
          # ccr.ccs.tencentyun.com
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Generate Tag List
        run: |
          docker system prune -af
          echo "TAGS<<EOF" >> $GITHUB_ENV
          echo  ${{ secrets.REGISTRY }}/yxing-xyz/linux:arch >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./archlinux/rootfs.Dockerfile
          context: ./archlinux
          tags: ${{ env.TAGS }}
